#!/usr/bin/env bash
# Roll the org `locks/` package out to every *-lib-core in orgs.tsv.
#
#   templates/lib-core/fanout.sh --issue DEN-123 [--orgs orgs.tsv] [--codes ~/codes] [--no-push] [--only org,org]
#
# Per org, in order, logging every step to stdout:
#   1. ensure ~/codes/<local_dir>/<lib_core_repo> exists — clone it, or when the
#      repository does not exist on GitHub, create it (private) and initialize
#      it with the generated files on main;
#   2. run gen_org_locks.py --commit, which builds the DEN-backed rollout
#      branch from the fetched remote default branch without touching the
#      working tree (safe on dirty or parked checkouts);
#   3. push the branch and open a draft PR (skipped with --no-push).
#
# Never rebases, stashes, resets, or commits onto main of an existing repo.
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
orgs="$here/orgs.tsv"
codes="$HOME/codes"
push=1
only=""
issue=""

while [ $# -gt 0 ]; do
  case "$1" in
    --orgs) orgs=$2; shift 2 ;;
    --codes) codes=$2; shift 2 ;;
    --no-push) push=0; shift ;;
    --only) only=$2; shift 2 ;;
    --issue) issue=$2; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [[ ! "$issue" =~ ^DEN-[0-9]+$ ]]; then
  echo "--issue must be a Linear identifier such as DEN-123" >&2
  exit 2
fi
branch="$issue/ores-locks-and-leases"

log() { printf '[fanout %s] %s\n' "$(date '+%H:%M:%S')" "$*"; }

if [ "$push" = 1 ] && ! gh auth status >/dev/null 2>&1; then
  log "gh is not authenticated; run 'gh auth login' or pass --no-push"; exit 1
fi

total=0; done_ok=0; failed=()
while IFS=$'\t' read -r org prefix repo interfaces local_dir; do
  case "$org" in ''|'#'*) continue ;; esac
  if [ -n "$only" ] && ! grep -q "\(^\|,\)$org\(,\|$\)" <<<"$only"; then continue; fi
  total=$((total + 1))
  path="$codes/$local_dir/$repo"
  log "== $org/$repo (prefix $prefix, interfaces $interfaces) -> $path"
  if (
    set -e
    if [ ! -e "$path/.git" ]; then
      mkdir -p "$codes/$local_dir"
      if gh repo view "$org/$repo" >/dev/null 2>&1; then
        log "cloning $org/$repo"
        gh repo clone "$org/$repo" "$path" -- --quiet
      else
        log "$org/$repo does not exist on GitHub; creating it (private) with the generated package on main"
        mkdir -p "$path" && git -C "$path" init -q -b main
        python3 "$here/gen_org_locks.py" --repo "$path" --org "$org" --prefix "$prefix" --interfaces "$interfaces"
        cat > "$path/README.md" <<EOF
# $repo

Canonical \`lib-core\` repository for [\`$org\`](https://github.com/$org): the
server-side core library (ORM boundary, shared behavior) consumed by the
org's \`*-api-server.rs\`, \`*-web-server.rs\` and admin servers through
zed-pkg. Client-side code lives in \`$prefix-pub-lib-core\`.

- Locks: \`locks/\` wraps ORESoftware/ores-locks-and-leases with this org's
  key prefix and catalog (see \`locks/README.md\`).
- Contracts: TypeSpec + JSON Schema, checked by ORESoftware/ores-contracts;
  shared interfaces come from \`$org/$interfaces\`.
- Runtimes: Rust, TypeScript, Dart, Gleam.
EOF
        printf '/target/\n**/target/\n**/node_modules/\n**/dist/\n**/.dart_tool/\n**/build/\n/.vendor/\n/.zed/\n/.ores/\n.env\n.env.*\n.DS_Store\n' > "$path/.gitignore"
        while IFS= read -r generated; do
          git -C "$path" add -- "$generated"
        done < <(python3 "$here/gen_org_locks.py" --repo "$path" --org "$org" --prefix "$prefix" --interfaces "$interfaces" --stdout)
        git -C "$path" add -- README.md .gitignore
        git -C "$path" commit -q -m "feat: initialize $repo with the org locks package

Generated by ORESoftware/ores-locks-and-leases templates/lib-core.

Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01P6vFcfS49sFvXjKFeWf2Kz"
        if [ "$push" = 1 ]; then
          gh repo create "$org/$repo" --private --source "$path" --remote origin --push \
            --description "Canonical $org core library (server-side); locks via ORESoftware/ores-locks-and-leases"
          log "created and pushed $org/$repo"
        fi
        log "== $org/$repo: initialized"
        exit 0
      fi
    fi

    log "fetching origin (tracking refs only)"
    git -C "$path" fetch -q --all --prune
    default_branch=$(gh repo view "$org/$repo" --json defaultBranchRef --jq .defaultBranchRef.name)
    python3 "$here/gen_org_locks.py" --repo "$path" --org "$org" --prefix "$prefix" --interfaces "$interfaces" --branch "$branch" --base-ref "origin/$default_branch" --commit
    if [ "$push" = 1 ]; then
      log "pushing $branch"
      git -C "$path" push -q -u origin "$branch"
      if gh pr view "$branch" --repo "$org/$repo" >/dev/null 2>&1; then
        log "PR already open for $branch"
      else
        gh pr create --repo "$org/$repo" --draft --head "$branch" \
          --title "$issue: consume ORESoftware/ores-locks-and-leases with the org key prefix and lock catalog" \
          --body-file - <<EOF
Linear: https://linear.app/denman/issue/$issue

Adds the nested \`locks/\` zed package — Rust, TypeScript, Dart, Gleam and Go wrappers over the shared fiducia-lease + Postgres-advisory-lock routines, every key prefixed \`$org/<domain>/<name>\` — plus the org lock catalog as a dual TypeSpec + JSON Schema contract (ores-contracts), and the root \`.zpkg.toml\` dependencies on \`ORESoftware/ores-locks-and-leases\` and \`$org/$interfaces\`.

Generated by \`ores-locks-and-leases/templates/lib-core/gen_org_locks.py\`; edit \`locks/catalog.json\` and re-run rather than editing the runtime slices by hand.

Draft until the generated Rust, Go, TypeScript, Dart, Gleam, TypeSpec and JSON Schema checks are green for the exact branch head.
EOF
        log "opened draft PR on $org/$repo"
      fi
    fi
    log "== $org/$repo: ok"
  ); then
    done_ok=$((done_ok + 1))
  else
    failed+=("$org/$repo")
    log "== $org/$repo: FAILED (continuing)"
  fi
done < "$orgs"

log "done: $done_ok/$total ok"
if [ ${#failed[@]} -gt 0 ]; then log "failed: ${failed[*]}"; exit 1; fi
